# Generated by Django 3.2.25 on 2024-07-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadisticasdeuda',
            name='edad_maxima',
        ),
        migrations.RemoveField(
            model_name='estadisticasdeuda',
            name='edad_minima',
        ),
        migrations.RemoveField(
            model_name='estadisticassalario',
            name='edad_maxima',
        ),
        migrations.RemoveField(
            model_name='estadisticassalario',
            name='edad_minima',
        ),
        migrations.AddField(
            model_name='estadisticasdeuda',
            name='institution',
            field=models.CharField(choices=[('Banco Itau', 'Banco Itau'), ('Banco Bice', 'Banco Bice'), ('Banco Estado', 'Banco Estado'), ('Banco Chile', 'Banco Chile'), ('Banco Santander', 'Banco Santander'), ('Banco BCI', 'Banco Bci'), ('Banco Falabella', 'Banco Falabella'), ('Hites', 'Hites')], default='Banco Default', max_length=100),
        ),
        migrations.AddField(
            model_name='estadisticassalario',
            name='institution',
            field=models.CharField(choices=[('Banco Itau', 'Banco Itau'), ('Banco Bice', 'Banco Bice'), ('Banco Estado', 'Banco Estado'), ('Banco Chile', 'Banco Chile'), ('Banco Santander', 'Banco Santander'), ('Banco BCI', 'Banco Bci'), ('Banco Falabella', 'Banco Falabella'), ('Hites', 'Hites')], default='Banco Default', max_length=100),
        ),
    ]
