# Generated by Django 3.2.25 on 2024-07-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20240721_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticasdeuda',
            name='cantidad_datos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticassalario',
            name='cantidad_datos',
            field=models.IntegerField(default=0),
        ),
    ]
