# Generated by Django 3.2.25 on 2024-07-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20240721_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadisticassalario',
            name='institution',
        ),
    ]
