# Generated by Django 3.2.25 on 2024-07-19 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(choices=[('Banco Itau', 'Banco Itau'), ('Banco Bice', 'Banco Bice'), ('Banco Estado', 'Banco Estado'), ('Banco Chile', 'Banco Chile'), ('Banco Santander', 'Banco Santander'), ('Banco BCI', 'Banco Bci'), ('Banco Falabella', 'Banco Falabella'), ('Hites', 'Hites')], max_length=100)),
                ('amount', models.IntegerField()),
                ('due_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='scoring.client')),
            ],
        ),
    ]
