# Generated by Django 3.2.25 on 2024-07-22 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_client_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='due_date',
            new_name='dueDate',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='sentAt',
        ),
    ]
